Public Class Procedimientos

    Public Const SP_ELIMINAR_PESABLES_Y_DUPLICADOS As String = "EXECUTE [SP_ELIMINAR_PESABLES_Y_DUPLICADOS] @id_inventario= {0}"
    Public Const SP_ACTUALIZAR_ARTICULO_SECTOR As String = "EXECUTE [SP_ACTUALIZAR_ARTICULO_SECTOR] @id_inventario= {0}"
    Public Const SP_ELIMINAR_SECTORES_NO_CUBIERTOS As String = "EXECUTE [SP_ELIMINAR_SECTORES_NO_CUBIERTOS] @id_inventario= {0}"
    Public Const SP_ELIMINAR_ARTICULOS_INVENTARIO As String = "EXECUTE [SP_ELIMINAR_ARTICULOS_INVENTARIO] @id_inventario= {0}"
    Public Const SP_TOMAR_MAESTRO_ARTICULOS As String = "EXECUTE [SP_TOMAR_MAESTRO_ARTICULOS] @id_inventario= {0}"
    Public Const SP_CARGAR_INVENTARIO_PRODUCTOS As String = "EXECUTE [SP_CARGAR_INVENTARIO_PRODUCTOS] @id_inventario= {0}"
    Public Const SP_CARGAR_INVENTARIO_PRODUCTO_SECTOR As String = "EXECUTE [SP_CARGAR_INVENTARIO_PRODUCTO_SECTOR] @id_inventario= {0}"
    Public Const SP_CARGAR_EXISTENCIA_NUEVO_INVENTARIO As String = "EXECUTE [SP_CARGAR_EXISTENCIA_NUEVO_INVENTARIO] @id_inventario= {0}"


End Class
